In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

class MyFakeClassifier(BaseEstimator):
    def fit(self,X,y):
        pass
    
    def predict(self,X):
        return np.zeros((len(X),1), dtype=bool)

In [2]:
# digits 확인
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
digits.data.shape

(1797, 64)

In [4]:
# digits번호가 7번이면 True이고 이를 astype(int)로 1로 변환
#7번이 아니면 False이고 0으로 변환
y = (digits.target==7).astype(int)
y

array([0, 0, 0, ..., 0, 0, 0])

In [5]:
# 학습 / 테스트 데이터 세드로 분리
X_train, X_test, y_train, y_test = train_test_split(digits.data, y,random_state=11)

In [6]:
X_train

array([[ 0.,  0.,  3., ..., 12., 14.,  7.],
       [ 0.,  1.,  9., ..., 10.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ..., 16., 13.,  1.],
       [ 0.,  1., 11., ..., 13., 16.,  5.],
       [ 0.,  0.,  6., ...,  6.,  0.,  0.]])

In [9]:
# 불균형한 레이블 데이터 분포도 확인
pd.Series(y_test).value_counts()

0    405
1     45
dtype: int64

In [10]:
# Dummy Classifier로 학습/예측/정확도 평가

fack_cl = MyFakeClassifier()
fack_cl.fit(X_train,y_train)
fackPred = fack_cl.predict(X_test)
accuracy = accuracy_score(y_test,fackPred)
print('정확도 : ',np.round((accuracy),3))

정확도 :  0.9


In [14]:
from sklearn.metrics import confusion_matrix
#MNIST의 fakepred
confusion_matrix(y_test,fackPred)

array([[405,   0],
       [ 45,   0]])

In [16]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

class MyFakeClassifier(BaseEstimator):
    def fit(self,X,y):
        pass
    
    def predict(self,X):
        return np.zeros((len(X),1), dtype=bool)

digit = load_digits()
y = (digits.target==7).astype(int)
X_train, X_test, y_train, y_test = train_test_split(digits.data, y,random_state=11)
fake_clf = MyFakeClassifier()
fake_clf.fit(X_train,y_train)
fakepred = fake_clf.predict(X_test)

In [2]:
# 오차행렬, 정확도, 정밀도, 재현율을 한꺼번에 계산하는 함수
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred) #오차행렬
    accuracy = accuracy_score(y_test, pred) # 정확도
    precision = precision_score(y_test, pred)# 정밀도
    recall = racall_score(y_test,pred) #재현율
    
    print('오차행렬')
    print(confusion)
    print('정확도 : {0:.3f}, 정밀도 : {1:.3f}, 재현율 : {2:.3f})

SyntaxError: EOL while scanning string literal (<ipython-input-2-7429f1037e13>, line 12)

In [3]:
from sklearn.preprocessing import Binarizer

X=[[1,-1,2],
  [2,0,0],
  [0,-1.1,1.2]]

# 기준값보다 같거나 작으면 0을 , 크면 1을 반환
binarizer = Binarizer(threshold=1.0)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
