<a href="https://colab.research.google.com/github/InTaewoo/multicampus-education/blob/main/python/pandas/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random 

df = pd.DataFrame(np.random.rand(6,3),index = [['a','a','b','b','c','c'],[1,2,1,2,1,2]],columns=['c1','c2','c3'])

In [ ]:
df

c1        c2        c3
a 1  0.844293  0.064236  0.846544
  2  0.609664  0.380671  0.097134
b 1  0.439968  0.878171  0.389759
  2  0.776491  0.725272  0.545538
c 1  0.347500  0.261308  0.233765
  2  0.388650  0.887305  0.975745

In [ ]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
# 데이터분석을 위한 파이썬 철저 입문
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s1.values

array([10, 20, 30, 40, 50])

In [ ]:
s2 = pd.Series(['a','b','c',1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [ ]:
pd.Series([np.nan,10,30])

0     NaN
1    10.0
2    30.0
dtype: float64

# 데이터연산


In [ ]:
import pandas as pd
import numpy as np
s = pd.Series(np.random.randint(0,10,5))
s

0    7
1    9
2    9
3    7
4    3
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),columns=['A','B','C'])
df

A  B  C
0  4  8  1
1  6  3  8
2  8  2  3

In [ ]:
np.exp(s)

0    1096.633158
1    8103.083928
2    8103.083928
3    1096.633158
4      20.085537
dtype: float64

In [ ]:
np.cos(df * np.pi /4)

A             B         C
0 -1.000000e+00  1.000000e+00  0.707107
1 -1.836970e-16 -7.071068e-01  1.000000
2  1.000000e+00  6.123234e-17 -0.707107

In [ ]:
s1 = pd.Series([1,3,5,7,9],index = [0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10],index = [1,2,3,4,5])
s1 + s2 

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2,fill_value=0) #Nan 대신에 0이 들어감

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),columns=list('ACD'))
df1

A   C   D
0  10   5   5
1   2   4  13
2   3  17   5

In [ ]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),columns=list('BAECD'))
df2

B   A   E   C   D
0   5  18   5  12   5
1  16  10   0  17  13
2  11  12  17  17  18
3  13  10  16  17  10
4   3   5   2   7  15

In [ ]:
df1 + df2

A   B     C     D   E
0  28.0 NaN  17.0  10.0 NaN
1  12.0 NaN  21.0  26.0 NaN
2  15.0 NaN  34.0  23.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
fvalue = df1.stack().mean()
df1.add(df2,fill_value=fvalue)

A          B          C          D          E
0  28.000000  12.111111  17.000000  10.000000  12.111111
1  12.000000  23.111111  21.000000  26.000000   7.111111
2  15.000000  18.111111  34.000000  23.000000  24.111111
3  17.111111  20.111111  24.111111  17.111111  23.111111
4  12.111111  10.111111  14.111111  22.111111   9.111111

# 연산자 범용함수


In [ ]:
a = np.random.randint(1,10,(3,3))
a

array([[3, 4, 2],
       [7, 4, 8],
       [2, 9, 8]])

In [ ]:
df = pd.DataFrame(a,columns=list('ABC'))
df

A  B  C
0  3  4  2
1  7  4  8
2  2  9  8

In [ ]:
df + df.iloc[0]

A   B   C
0   6   8   4
1  10   8  10
2   5  13  10

In [ ]:
df.add(df.iloc[0])

A   B   C
0   6   8   4
1  10   8  10
2   5  13  10

In [ ]:
a 

array([[3, 4, 2],
       [7, 4, 8],
       [2, 9, 8]])

In [ ]:
a-a[0]

array([[ 0,  0,  0],
       [ 4,  0,  6],
       [-1,  5,  6]])

In [ ]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  4  0  6
2 -1  5  6

In [ ]:
a

array([[3, 4, 2],
       [7, 4, 8],
       [2, 9, 8]])

In [ ]:
a *a[0]

array([[ 9, 16,  4],
       [21, 16, 16],
       [ 6, 36, 16]])

In [ ]:
df * df.iloc[1]

A   B   C
0  21  16  16
1  49  16  64
2  14  36  64

In [ ]:
df.mul(df.iloc[1])

A   B   C
0  21  16  16
1  49  16  64
2  14  36  64

In [ ]:
df.truediv(df.iloc[0])

A     B    C
0  1.000000  1.00  1.0
1  2.333333  1.00  4.0
2  0.666667  2.25  4.0

In [ ]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 0],
       [2, 1, 0]])

In [ ]:
df

A  B  C
0  3  4  2
1  7  4  8
2  2  9  8

In [ ]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  0  0
2  2  1  0

In [ ]:
a ** a[0]

array([[  27,  256,    4],
       [ 343,  256,   64],
       [   8, 6561,   64]])

In [ ]:
df.pow(df.iloc[0])

A     B   C
0   27   256   4
1  343   256  64
2    8  6561  64

# 정렬

In [ ]:
s = pd.Series(range(5),index=['a','d','w','z','e'])
s

a    0
d    1
w    2
z    3
e    4
dtype: int64

In [ ]:
s.sort_index()

a    0
d    1
e    4
w    2
z    3
dtype: int64

In [ ]:
s.sort_values()

a    0
d    1
w    2
z    3
e    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,10,(4,4)),index=[2,4,1,3],
                  columns=list('BDAC'))
df

B  D  A  C
2  7  6  4  7
4  9  6  1  1
1  0  5  0  9
3  2  2  6  5

In [ ]:
df.sort_index()

B  D  A  C
1  0  5  0  9
2  7  6  4  7
3  2  2  6  5
4  9  6  1  1

In [ ]:
df.sort_values(by=['A','C']) #2차원일 경우 속성값을 지정해야됨

B  D  A  C
1  0  5  0  9
4  9  6  1  1
2  7  6  4  7
3  2  2  6  5

In [ ]:
df.sort_index(axis=1)

A  B  C  D
2  4  7  7  6
4  1  9  1  6
1  0  0  9  5
3  6  2  5  2

# 순위(Ranking)

In [ ]:
s = pd.Series([-2,3,5,-2,4,0,19,3])
s

0    -2
1     3
2     5
3    -2
4     4
5     0
6    19
7     3
dtype: int64

In [ ]:
s.rank()

0    1.5
1    4.5
2    7.0
3    1.5
4    6.0
5    3.0
6    8.0
7    4.5
dtype: float64

In [ ]:
word_dict = {'apple':'사과',
             'banana':'바나나',
             'carrot':'당근'}

In [ ]:
word_dict

{'apple': '사과', 'banana': '바나나', 'carrot': '당근'}

In [ ]:
frequency_dict ={'apple':3,
                 'banana':5,
                 'carrot':7}

In [ ]:
word =pd.Series(word_dict)
word

apple      사과
banana    바나나
carrot     당근
dtype: object

In [ ]:
frequency =  pd.Series(frequency_dict)
frequency

apple     3
banana    5
carrot    7
dtype: int64

In [ ]:
total = pd.DataFrame({'word':word,'frequency':frequency})
total

word  frequency
apple    사과          3
banana  바나나          5
carrot   당근          7

In [ ]:
importance_dict = {'apple':5,
                   'banana':10,
                   'carrot':4} 
importance_dict

                  

{'apple': 5, 'banana': 10, 'carrot': 4}

In [ ]:
total = pd.DataFrame({'word':word,'frequency':frequency,
                      'important':importance_dict})
total

word  frequency  important
apple    사과          3          5
banana  바나나          5         10
carrot   당근          7          4